Add config in RCA
st054745/RCA pull request #26
Opened 2019-03-06 14:41 UTC by st054745

Добавлен конфиг для RCA

2019-03-07 05:55 UTC, st054745 commented
Надо еще вынести пути логирования в конфиг

2019-03-14 19:31 UTC, danila19991 requested changes

2019-03-14 19:31 UTC, danila19991 commented on System/main.cpp
> +public:
private

2019-03-14 19:31 UTC, danila19991 commented on System/main.cpp
> +    }
исключительно из интереса: Что произойдет если файл уже открыт?

2019-03-14 19:31 UTC, danila19991 commented on System/main.cpp
> +};
Где конструкторы и операторы перемещения?

2019-03-14 20:41 UTC, st054745 commented
Сделал запрошенные изменения. Осталось добить захардкоженный путь к конфигу

2019-03-14 20:44 UTC, danila19991 commented on System/main.cpp
> +    }
нет так тоже можно, но на мой взгляд более логично закрыть текущий файл и открыть новый

2019-03-14 20:53 UTC, st054745 commented on System/main.cpp
> +    }
Да я в итоге просто поставил проверку, открыт файл или нет, думаю пойдет и так

2019-03-14 20:53 UTC, danila19991 commented on System/main.cpp
> +    }
ладно

2019-03-14 21:05 UTC, danila19991 submitted a review, later dismissed

2019-03-14 21:18 UTC, st054745 commented
А с путями до конфига что делать?

2019-03-22 19:53 UTC, danila19991 reviewed
Есть несколько вопросов.

2019-03-22 19:53 UTC, danila19991 commented on System/main.cpp
>      }
А что будет если мы захотим поменять имя файл в процессе работы?

2019-03-22 19:53 UTC, danila19991 commented on System/main.cpp
> +    }
Вроде как деструктор тоже должен быть приватным.

2019-03-22 19:53 UTC, danila19991 commented on System/main.cpp
>      QTextStream consoleStream(stdout);
Может в singleton держать поток и выдавать его?

2019-03-23 17:39 UTC, danila19991 reviewed
some questions

2019-03-23 17:39 UTC, danila19991 commented on System/main.cpp
> +    }
Где удаление QFile?

2019-03-23 18:31 UTC, danila19991 approved these changes
Ok

2019-03-23 18:43 UTC, merged